[package]
name = "how-to-use-punycode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base36 = "0.0.1"
idna = "0.3.0"
punycode = "0.4.1"
regex = "1.7.3"
